import Link from 'next/link';
import React from 'react';
export const metadata = {
    title: "About",
    description: "Generated by create next app",
};
const Aboutlayout = ({children}) => {
    return (
        <main className='mt-5 '>
            <nav>
                <ul className="flex gap-6">
                    <li><Link href="/about/mission">mission</Link></li>
                    <li><Link href="/about/vision">Vissoin</Link></li>

                </ul>
            </nav>
            {children}
        </main>
    );
};

export default Aboutlayout;